#!/bin/bash
# The `bash HOWTO` command given at the command line within the `mdgBookSVG3Kit-main` directory
# in your computer will automatically carry out the following steps leading to the creation of the 
# collection book: `mdgBookSVG3v1.pdf`.
# 
# Create three sub-folders: `bin`, `images`, `res`, under the `mdgBookSVG-master` directory
#		`bin` - folder for Bash files: mdg23mid+svg.sh, mdg32midRndN-svg.sh, mdgEntriesSVGkn2.sh
#		`images` - folder for image files for book cover/title page: 1ed.png, FrontCover.pdf
# 	`res` - folder for ABC, SVG, PDF output files; initially contains: 
#		012TAB.pdf - crosstable for one-die outcome vs. measure number of minuet/trio 
#		knbgr-easy-minuet.abc - table of measures for the minuets
#		knbgr-easy-trio,abc - table of measures for the trios
#		hyperref.cfg - file containing the \hypersetup{} keyvalues for the \hyperref pkg
#		mdg4.bib - bibliography file for the book
#		mdgBookSVG3v1.tex - main LaTeX file for book 
#		mdgBookSVG3v1-cover.tex - LaTeX file for cover page

	mkdir bin images res
	mv *.sh bin
	mv 1ed.png images; mv FrontCover.pdf images
	mv 012TAB.pdf res; mv knbgr-easy-minuet.abc res; mv knbgr-easy-trio.abc res
	mv hyperref.cfg res; mv mdg4.bib res
	mv *.tex res

# Change directory res folder then, for each bash file in `bin`, create a link 
# from `bib` to `res`
	
	cd res 
	ln -s ../bin/*.sh . 

# Within `res` directory, generate nnn MDGs (nnn is number of MDG minuets in book to be created)
# For 250 minuets to be generated: nnn=250.

	./mdg32midRndN-svg.sh 28

# Generate a list of SVGs created by the previous step:

	ls --color=never knbgr*.svg > svgList.txt

# Create a list of figure entries for LaTeX file; *.pdf_tex files are also created using inkscape

	./mdgEntriesSVGkn2.sh svgList.txt

# Change the font sizes of titles, subtitles, repeat signs in each K516f*.pdf_tex file

	sed -i 's/\\textbf{knbgr/\\textbf{\\footnotesize \\tt knbgr/g' *.pdf_tex
	sed -i 's/\\textbf{Perm/\\textbf{\\footnotesize \\tt Perm/g' *.pdf_tex
	sed -i 's/\\textit{3}/\\textit{\\footnotesize 3}/g' *.pdf_tex
	sed -i 's/\\smash{2}/\\smash{\\footnotesize 2}/g' *.pdf_tex
	sed -i 's/\\textit{tr}/\\textit{\\footnotesize tr}/g' *.pdf_tex
	sed -i 's/\\textbf{= 90/\\textbf{\\footnotesize = 90/g' *.pdf_tex

# Move svgList.txt.output to svgList.tex

	cp svgList.txt.output svgList.tex

# Remove trailing `001` from each svgList.tex entry 

	sed -i.OLD 's/001}/}/g' svgList.tex
	sed -i.OLD 's/001.mid}/.mid}/g' svgList.tex

# Create SVGs for knbgr-easy-minuet.pdf & knbgr-easy-trio.pdf (tables of measures); 
# also corresponding *pdf_tex files using inkscape

	abcm2ps -v -O= knbgr-easy-minuet.abc
	inkscape -D -z --file=knbgr-easy-minuet001.svg --export-pdf=knbgr-easy-minuet001.pdf --export-latex
	inkscape -D -z --file=knbgr-easy-minuet002.svg --export-pdf=knbgr-easy-minuet002.pdf --export-latex

	abcm2ps -v -O= knbgr-easy-trio.abc
	inkscape -D -z --file=knbgr-easy-trio001.svg --export-pdf=knbgr-easy-trio001.pdf --export-latex
	inkscape -D -z --file=knbgr-easy-trio002.svg --export-pdf=knbgr-easy-trio002.pdf --export-latex
	inkscape -D -z --file=knbgr-easy-trio003.svg --export-pdf=knbgr-easy-trio003.pdf --export-latex

##	and "_" (5x); and \url{---}for URL

	sed -i.OLD '/http/s/_/\\_/g' knbgr-easy-minuet001.pdf_tex
	sed -i.OLD '/put(0.31773628,1.28500584)/s/\\textit{3}/\\textit{${}$3}/' knbgr-easy-minuet001.pdf_tex
	sed -i.OLD 's/\[http/\\scriptsize\[from \\url{http/g' knbgr-easy-minuet001.pdf_tex
	sed -i.OLD 's/Philipp)\]/Philipp)}\]/g' knbgr-easy-minuet001.pdf_tex

	sed -i.OLD '/http/s/_/\\_/g' knbgr-easy-trio001.pdf_tex
	sed -i.OLD '/put(0.28950565,1.22414527)/s/\\textit{3}/\\textit{${}$3}/' knbgr-easy-trio001.pdf_tex
	sed -i.OLD 's/\[http/\\scriptsize\[from \\url{http/g' knbgr-easy-trio001.pdf_tex
	sed -i.OLD 's/Philipp)\]/Philipp)}\]/g' knbgr-easy-trio001.pdf_tex

##	- add "\scriptsize" before every "tr" and "3-plet" (symbol for trill ornament)  

	sed -i.OLD 's/\\textit{tr}/\\textit{\\scriptsize tr}/g' knbgr-*.pdf_tex 
	sed -i.OLD 's/\[t\]{c}\\textit{3}/\[t\]{c}\\textit{\\scriptsize 3}/g' knbgr-*.pdf_tex
	sed -i.OLD 's/\[t\]{l}\\textit{/\[t\]{c}\\texttt{\\footnotesize /g' knbgr-*.pdf_tex
	
# Generate the PDF

	pdflatex -synctex=1 -interaction=nonstopmode -shell-escape mdgBookSVG3v1.tex
	bibtex mdgBookSVG3v1.aux
	pdflatex -synctex=1 -interaction=nonstopmode -shell-escape mdgBookSVG3v1.tex
	pdflatex -synctex=1 -interaction=nonstopmode -shell-escape mdgBookSVG3v1.tex

###
##
#
